### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by lpetrovic05** [offbynull/portmapper#25]
Is it possible to use the portmapper under another licence, like CDDL?

**Comment by offbynull** [comment]
Hi,

I use LGPL to encourage people to contribute changes back to the project
but I can change to apache or bsd if it better suites your scenario. It
would be good if you could describe your scenario in this ticket.

I'm not too familiar with CDDL.

Let me know if apache or bsd works for you.

**Comment by lpetrovic05** [comment]
Hi,
The problem I have with the LGPL is that I would like to bundle everything in a single jar file that a user can easily run on his desktop, and section 4.d prevents me from doing so. Apache or BSD would be great. I can also promise to contribute if I do end up making any changes to the library :)

**Comment by offbynull** [comment]
Understood.

I'll update the license and cut a new release in the next couple of days.

Will update this ticket once complete.

Todo:
- update source license headers
- update checkstyle license header check
- update maven license tag
- update github license info

**Comment by lpetrovic05** [comment]
Thanks a lot

**Comment by offbynull** [comment]
2.0.2 has been released. License has been changed to Apache2.

It should be available from Maven central shortly.

**Comment by lpetrovic05** [comment]
Thank you
