### ISSUE TITLE
PortMapperFactory.discover(networkBus, processBus) sometimes returning empty list 

### ISSUE THREAD

**Issue by davidhewitt128** [offbynull/portmapper#32]
It spends a long time in the method `PortMapperFactory.discover(networkBus, processBus)`, maybe a minute. Is this normal?

Sometimes returns an empty list but when it doesn't the example you've provided works fine.
Using the web interface of my router shows that UPnP is been mapped correctly.

Maybe it's the network configuration I have.
Thanks.

**Comment by offbynull** [comment]
Can you provide logs for the cases where it provides an empty list vs a non-empty list?

**Comment by offbynull** [comment]
Also, that amount of time could be normal. It could be trying requests that failed for whatever reason or otherwise probing your network for routers.
