### ISSUE TITLE
Does this support regular UPNP?

### ISSUE THREAD

**Issue by jredfox** [offbynull/portmapper#38]
hi I have been looking for a port opener simple code to implement for UPNP and NAT-PMP so when one fails I use the other. Does this support regular UPNP if not could you add support? I tried cling but, there were compile errors everywhere after a maul painful installation.

I would also like some examples of how to open/keep-open a port as well as how to close it. I am not familiar with open/closing ports if your app closes via task manager does the port still stay open?

**Comment by offbynull** [comment]
Hey,

It does support UPnP. The quickstart example in the README shows you how to open a port, keep it open, and then close it. If the application is terminated abruptly (e.g. via task manager), the port stays open for some duration. There's nothing you can really do work around this.

The README should cover everything you need to know.
