### ISSUE TITLE
RegexUtils.findAllIpv4Addresses does not find gateway properly

### ISSUE THREAD

**Issue by icaliskan** [offbynull/portmapper#7]
my gateway ip is 10.6.0.254 but expression matches 10.6.0.2

**Comment by icaliskan** [comment]
i find this regexp. this works fine for me. may be you can use it. 

"(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}"

**Comment by offbynull** [comment]
Hi. Thank you for the bug report.

I'll look in to this on the weekend and hopefully deploy a fixed version soon.

**Comment by offbynull** [comment]
I've committed a change that should fix this. Please take a look if you have a moment to spare.

I'll publish a new version with this fix sometime this month.

**Comment by offbynull** [comment]
Closing the ticket. This change won't be released until 2.0.

**Comment by offbynull** [comment]
Re-opening as a reminder to test.

**Comment by offbynull** [comment]
Tested and works.
